expose:
  Args: 
    - --v
    - 4
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded

cleanup:
  Args: 
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
exposecontroller:
  config:
    domain: test.wahed.com
    exposer: Ingress
    http: "true"
    tlsacme: ""
    pathmode: ""
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
jenkins:
  servers:
    gitea: []
    ghe: []
    global:
      envvars:
        DOCKER_REGISTRY: 630728872373.dkr.ecr.eu-central-1.amazonaws.com
        TILLER_NAMESPACE: kube-system
  enabled: null
prow:
  user: ""
  hmactoken: ""
  oauthtoken: ""
pipelinesecrets:
  dockerconfig: ""
controllerbuild:
  enabled: null
